### ISSUE TITLE
commiteth test

### ISSUE THREAD

**Issue by tpatja** [tpatja/commiteth-demo-repo#1]

**Comment by commiteth** [comment]
Current balance: 0.0000 ETH
![QR Code](http://91.145.77.247:3000/qr/tpatja/commit-eth-demo-repo/bounty/1/b877ab34328be94a37051d4c4ffbda9da5c97da94c5e9f61c697e71c97bebec4/qr.png)
[http://91.145.77.247:3000](http://91.145.77.247:3000)

**Comment by commiteth** [comment]
Current balance: 1.20000000 ETH
![QR Code](http://91.145.77.247:3000/qr/tpatja/commiteth-demo-repo/bounty/1/ab02a247694823124eb0782a49498004d4de066d8e8a9fd81ecc6a615120feab/qr.png)
[http://91.145.77.247:3000](http://91.145.77.247:3000)
