### ISSUE TITLE
One more test issue

### ISSUE THREAD

**Issue by tpatja** [tpatja/commiteth-demo-repo#22]

**Comment by commiteth** [comment]
![Contract deploying](http://91.145.77.247:3000/img/deploying_contract.png)

**Comment by commiteth** [comment]
![Contract deploying](https://commiteth.com/img/deploying_contract.png)

**Comment by commiteth** [comment]
Current balance: 0.66000000
Contract address: 0x72571d819c0d0640baac92614371d509ac60e42a
![QR Code](http://91.145.77.247:3000/qr/tpatja/commiteth-demo-repo/bounty/22/8ac68b2b12a499db1009670f6cb1f2abddc861e2731e1501033d6d1ba46d954b/qr.png)
Network: Testnet
To claim this bounty sign up at [http://91.145.77.247:3000](http://91.145.77.247:3000)
