### ISSUE TITLE
One more demo issue

### ISSUE THREAD

**Issue by tpatja** [tpatja/commiteth-demo-repo#26]

**Comment by commiteth** [comment]
![Contract deploying](http://91.145.77.247:3000/img/deploying_contract.png)

**Comment by commiteth** [comment]
![Contract deploying](http://91.145.77.247:3000/img/deploying_contract.png)

**Comment by commiteth** [comment]
![Contract deploying](http://91.145.77.247:3000/img/deploying_contract.png)

**Comment by commiteth** [comment]
Current balance: 0.0 ETH
Contract address: 0x84196a119bd4b1aad288343d26016b16e50453b2
![QR Code](http://tpatja.duckdns.org:3000/qr/tpatja/commiteth-demo-repo/bounty/26/4ae095692017109369564ab4cb7c810f3d64088db9661c8bb0c06e66cc711c78/qr.png)
Network: Testnet (Rinkeby)
To claim this bounty sign up at [http://tpatja.duckdns.org:3000](http://tpatja.duckdns.org:3000)
