### ISSUE TITLE
Testing issue renaming

### ISSUE THREAD

**Issue by tpatja** [tpatja/commiteth-demo-repo#32]

**Comment by commiteth** [comment]
Current balance: 0.0 ETH
Contract address: 0xa230c418ff77b79023112ffdc12158bd4bdef15e
![QR Code](http://tpatja.duckdns.org:3000/qr/tpatja/commiteth-demo-repo/bounty/32/87ee26c64b3178962882bf0475a616e6ff4f6b3353583035ecf6bcba6c28c4f7/qr.png)
Network: Testnet (Rinkeby)
To claim this bounty sign up at [http://tpatja.duckdns.org:3000](http://tpatja.duckdns.org:3000)

**Comment by commiteth** [comment]
Current balance: 0.0 ETH
Contract address: 0xa30354f0881d144a1c88375f1abd1360b4e6fe4d
![QR Code](https://commiteth.com:444/qr/tpatja/commiteth-demo-repo/bounty/32/87ee26c64b3178962882bf0475a616e6ff4f6b3353583035ecf6bcba6c28c4f7/qr.png)
Network: Testnet (Rinkeby)
To claim this bounty sign up at [https://commiteth.com:444](https://commiteth.com:444)
To fund it, send ETH or ERC20 tokens to the contract address.
