### ISSUE TITLE
test issue for ERC20 support

### ISSUE THREAD

**Issue by tpatja** [tpatja/commiteth-demo-repo#33]

**Comment by commiteth** [comment]
Balance: 0.3300 ETH
Tokens: MLN: 2.23 SNT: 205.00
Contract address: [0xb157d60548c6efb04408e0b411c01afff82c5875](https://rinkeby.etherscan.io/address/0xb157d60548c6efb04408e0b411c01afff82c5875)
Network: Testnet (Rinkeby)
Paid to: 0xb157d60548c6efb04408e0b411c01afff82c5875

**Comment by commiteth** [comment]
![Contract deploying](https://commiteth.com:444/img/deploying_contract.png)

**Comment by commiteth** [comment]
![Contract deploying](https://commiteth.com:444/img/deploying_contract.png)

**Comment by commiteth** [comment]
Balance: 0.3600 ETH
Tokens: DNT: 0.00 GNO: 2.00 MLN: 100.00 SNT: 3303.32
Contract address: [0x7d8f06fc2d6511cf73bbfec90b0f0f81f88327ae](https://rinkeby.etherscan.io/address/0x7d8f06fc2d6511cf73bbfec90b0f0f81f88327ae)
Network: Testnet (Rinkeby)
Status: pending maintainer confirmation
Winner: 0x7d8f06fc2d6511cf73bbfec90b0f0f81f88327ae
