### ISSUE TITLE
Another test issue for ERC20 support

### ISSUE THREAD

**Issue by tpatja** [tpatja/commiteth-demo-repo#34]

**Comment by commiteth** [comment]
![Contract deploying](https://commiteth.com:444/img/deploying_contract.png)

**Comment by commiteth** [comment]
Balance: 0.5500 ETH
Tokens: SNT: 140.00
Contract address: [0x6ce173cd0b6851c1d5dde733a5bffd6dcf186889](https://rinkeby.etherscan.io/address/0x6ce173cd0b6851c1d5dde733a5bffd6dcf186889)
Network: Testnet (Rinkeby)
Paid to: tpatja

**Comment by commiteth** [comment]
Balance: 0.2000 ETH
Tokens: SNT: 140.00
Contract address: [0xbcffb83e843eb9493ad2e6dc6128e8b9bb3b0eec](https://rinkeby.etherscan.io/address/0xbcffb83e843eb9493ad2e6dc6128e8b9bb3b0eec)
Network: Testnet (Rinkeby)
Status: pending maintainer confirmation
Winner: 0xbcffb83e843eb9493ad2e6dc6128e8b9bb3b0eec
