### ISSUE TITLE
ERC20 test issue 3

### ISSUE THREAD

**Issue by tpatja** [tpatja/commiteth-demo-repo#37]

**Comment by commiteth** [comment]
Balance: 0.1100 ETH
Tokens: SNT: 1.10
Contract address: [0x002561b483b9b27bc29b332c13542e8a59ba2146](https://rinkeby.etherscan.io/address/0x002561b483b9b27bc29b332c13542e8a59ba2146)
Network: Testnet (Rinkeby)
Paid to: tpatja

**Comment by commiteth** [comment]
Balance: 0.0000 ETH
Contract address: [0x4a0087f0be88605ad0f54b2affec80c1f3c1ae0d](https://rinkeby.etherscan.io/address/0x4a0087f0be88605ad0f54b2affec80c1f3c1ae0d)
Network: Testnet (Rinkeby)
Status: pending maintainer confirmation
Winner: 0x4a0087f0be88605ad0f54b2affec80c1f3c1ae0d
