### ISSUE TITLE
Ropsten ERC20 test issue

### ISSUE THREAD

**Issue by tpatja** [tpatja/commiteth-demo-repo#45]

**Comment by commiteth** [comment]
![Contract deploying](https://commiteth.com:444/img/deploying_contract.png)

**Comment by commiteth** [comment]
![Contract deploying](https://commiteth.com:444/img/deploying_contract.png)

**Comment by commiteth** [comment]
Balance: 0.2000 ETH
Tokens: GNT: 0.00 SNT: 0.00
Contract address: [0xb48b031c51f91c87244aeb3c658276fee03ac166](https://ropsten.etherscan.io/address/0xb48b031c51f91c87244aeb3c658276fee03ac166)
Network: Testnet (Ropsten)
Paid to: tpatja
