### ISSUE TITLE
commiteth test2

### ISSUE THREAD

**Issue by tpatja** [tpatja/commiteth-demo-repo#6]

**Comment by commiteth** [comment]
Current balance: 0.40000000 ETH
![QR Code](http://91.145.77.247:3000/qr/tpatja/commiteth-demo-repo/bounty/6/10c7a2e93d8a91f2a0feef6574709b67708a0792f5ed356aae823771ba7cfc8d/qr.png)
[http://91.145.77.247:3000](http://91.145.77.247:3000)
