### ISSUE TITLE
commiteth test 3

### ISSUE THREAD

**Issue by tpatja** [tpatja/commiteth-demo-repo#9]

**Comment by commiteth** [comment]
Current balance: 0.00000000 ETH
![QR Code](http://91.145.77.247:3000/qr/tpatja/commiteth-demo-repo/bounty/9/539473e98c108a4e326ac85f66eb542140b823afbe2ff13b4787d7485f2c70a2/qr.png)
[http://91.145.77.247:3000](http://91.145.77.247:3000)
